theme: jekyll-theme-slate
title: Introducción a QGIS
description: Curso de introducción al programa SIG QGIS organizado por la Facultad de Geografía e Historia de la Universidad Complutense de Madrid 
